### ISSUE TITLE
Not working with Max count Reached

### ISSUE THREAD

**Issue by BirukTes** [FraserChapman/plunger#1]
It is not working currently with the added count of only 3 videos allowed. 

If the same video is refreshed three times, it reaches the max count.

It plays only audio, once the YT 3 count are reached... only option is to log out, in which case this extension is not required.

**Comment by FraserChapman** [comment]
Hi, thanks for the report...can I ask;

- Which browser are you using? 
- Which adblocker are you using?
- Can you give a link to an example video?

I am more than happy to take a look at this to see if I can see what the issue is  - FWIW I've just tested in Chromeand Edge whilst using "Adblock" (https://chromewebstore.google.com/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom) and don't have any issues myself. 

Really I would need some more information to see if I can reproduce the issue you are seeing. 

Thanks!

**Comment by BirukTes** [comment]
Hi @FraserChapman,

Here:
- Vivaldi
- uBlock Origin
- You can technically use any video... (https://youtu.be/XBzX_sKt5eY)

Thanks

**Comment by FraserChapman** [comment]
Hi @BirukTes, 

Thanks for sharing that information; I truly appreciate it!

I wasn't previously familiar with the Vivaldi browser, and it does seem intriguing...However, it falls outside the parameters of this project, as my focus is currently on Chrome, Firefox, and Edge. While I understand that both Chrome and Vivaldi support the same extensions through the Chrome Web Store, there may be some differences in compatibility. Because Vivaldi has unique customization options, some extensions may not work correctly in Vivaldi.

As I am sure you can imagine there is an immense challenge of testing every browser in combination with each ad blocker, and as such it's necessary to restrict the scope to a manageable extent.

That said, I've gone ahead and installed Vivaldi along with uBlock Origin to explore and understand the specific issue at hand. However, at this time, I'm unable to guarantee support for every possible browser and ad blocker pairing. 

Hope this makes sense, if I do have a fix and can offer support for Vivaldi I will update the project :)

**Comment by BirukTes** [comment]
Hi @FraserChapman,

Do not worry... but as far as I know Extension developers do not need to do anything to improve compatibility with Vivaldi, therefore we install directly from Chrome web store and Chrome Extensions work just fine. However, user agent is different and it also has its own Ad Block which I have disabled now and YT is not bothering me now (yet), I think then it might have been the Vivaldi built-in Ad-block that was being detected rather than uBlock or Plunger.

**Comment by FraserChapman** [comment]
@BirukTes Ah ok that makes sense, I did wonder about that when I installed it as it had a bunch of options for inbuilt blocking, disabling trackers, etc. How YT detects and this and displays the error in these cases might be slightly different to other ad-blockers. 

Annoyingly (ironically) at the moment I can't get blocked using an Vivaldi and ublock origin, so I can't see exactly what was happening in your case.  One issue might be how Vivaldi is handling the V3 manifest (that plunger uses). 

 I did read this on https://help.vivaldi.com/desktop/appearance-customization/extensions/
> In some instances, extensions built for the Chrome browser will behave differently when installed in Vivaldi, but for the most part your favourite Chrome extensions will work just fine in Vivaldi.

Still it is an interesting edge case so I will keep playing with it.  Thanks again for reporting this and for the updates, I really appreciate you taking the time to do so :)
